apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.namespace }}-${{ values.name }}
  namespace: argo-cd
  labels:
    app.kubernetes.io/managed-by: backstage
spec:
  project: default
  source:
    repoURL: https://github.com/arigsela/kubernetes
    targetRevision: main
    path: base-apps/${{ values.namespace }}-${{ values.name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true