apiVersion: v1
kind: Namespace
metadata:
  name: backstage-demo
  annotations:
    # System annotations for the namespace
    terasky.backstage.io/system: demo-system
    terasky.backstage.io/system-type: application
    terasky.backstage.io/domain: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: backstage-demo
  labels:
    app: demo-app
  annotations:
    # Core annotations for kubernetes-ingestor
    terasky.backstage.io/add-to-catalog: "true"
    terasky.backstage.io/system: demo-system
    terasky.backstage.io/owner: platform-team
    terasky.backstage.io/component-type: service
    terasky.backstage.io/lifecycle: production
    terasky.backstage.io/source-code-repo-url: https://github.com/arigsela/backstage-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: backstage-demo
  labels:
    app: demo-app
  annotations:
    # Service will be associated with the deployment
    terasky.backstage.io/add-to-catalog: "true"
    terasky.backstage.io/system: demo-system
    terasky.backstage.io/owner: platform-team
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: backstage-demo
  labels:
    app: demo-app
  annotations:
    # ConfigMap will be associated with the deployment
    terasky.backstage.io/add-to-catalog: "true"
    terasky.backstage.io/system: demo-system
data:
  index.html: |
    <html>
      <body>
        <h1>Demo App for Backstage Kubernetes Ingestor</h1>
        <p>This deployment is automatically discovered by the kubernetes-ingestor!</p>
      </body>
    </html>