apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.appName }}-catalog
  namespace: ${{ values.namespace }}
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/component: catalog
    backstage.io/kubernetes-id: ${{ values.appName }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.appName }}
    terasky.backstage.io/add-to-catalog: "true"
data:
  catalog-info.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: ${{ values.appName }}-mysql-db
      description: ${{ values.description | default('MySQL database for ' + values.appName) }}
      annotations:
        backstage.io/kubernetes-id: ${{ values.appName }}
        backstage.io/kubernetes-namespace: ${{ values.namespace }}
      links:
        # Vault Secret Management
        - url: ${{ values.vaultUrl }}/ui/vault/secrets/secret/show/${{ values.appName }}/DB_PASSWORD
          title: Database Password (Vault)
          icon: key
          type: admin
        
        # Monitoring & Observability
        - url: ${{ values.grafanaUrl }}/d/mysql-overview/mysql-database-overview?var-database=${{ values.databaseName }}&var-namespace=${{ values.namespace }}
          title: Grafana Dashboard
          icon: dashboard
          type: monitoring
        
        - url: https://prometheus.example.com/graph?g0.expr=mysql_up%7Bdatabase%3D%22${{ values.databaseName }}%22%7D&g0.tab=0
          title: Prometheus Metrics
          icon: dashboard
          type: monitoring
        
        # Database Administration
        - url: ${{ values.phpMyAdminUrl }}/index.php?db=${{ values.databaseName }}&server=${{ values.namespace }}-mysql
          title: phpMyAdmin
          icon: database
          type: admin
        
        # Kubernetes Resources
        - url: https://k8s-dashboard.example.com/#!/overview?namespace=${{ values.namespace }}
          title: Kubernetes Dashboard
          icon: dashboard
          type: infrastructure
        
        - url: https://argocd.example.com/applications/${{ values.namespace }}/${{ values.appName }}
          title: ArgoCD Application
          icon: docs
          type: deployment
        
        # Documentation & Support
        - url: https://wiki.example.com/display/PLATFORM/MySQL+Database+${{ values.appName }}
          title: Runbook
          icon: docs
          type: documentation
        
        - url: https://slack.com/app_redirect?channel=${{ values.slackChannel }}
          title: Support Channel (#platform-support)
          icon: chat
          type: support
        
        # Cost & Billing
        - url: https://cloud.example.com/billing/project/${{ values.appName }}?filter=mysql
          title: Cost Analysis
          icon: report
          type: cost
    spec:
      type: database
      owner: ${{ values.owner }}
      system: ${{ values.system }}
      lifecycle: ${{ values.environment }}