apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{ values.appName }}-secret
  namespace: ${{ values.namespace }}
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/instance: ${{ values.appName }}-mysql
    app.kubernetes.io/component: database-secret
    app.kubernetes.io/part-of: ${{ values.appName }}
    environment: ${{ values.environment }}
    backstage.io/kubernetes-id: ${{ values.appName }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: ${{ values.appName }}-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: ${{ values.appName }}
        property: DB_PASSWORD
