apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: ${{ values.namespace }}
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/instance: ${{ values.appName }}-vault
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: ${{ values.appName }}
    environment: ${{ values.environment }}
    backstage.io/kubernetes-id: ${{ values.appName }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"