apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.appName }}
  namespace: argo-cd
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/instance: ${{ values.appName }}-argocd
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: ${{ values.appName }}
    environment: ${{ values.environment }}
    backstage.io/kubernetes-id: ${{ values.appName }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: default
  source:
    repoURL: https://github.com/arigsela/kubernetes
    targetRevision: main
    path: base-apps/${{ values.appName }}
    directory:
      exclude: 'catalog-info.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10